version = 1
test_patterns = ["**/__tests__/**","**/*.test.*","**/*.spec.*"]
exclude_patterns = ["node_modules/**",".next/**",".vercel/**",".vercel/output/**","out/**","dist/**","build/**","coverage/**","public/**/*.min.*"]

[[analyzers]]
name = "javascript"
enabled = true
  [analyzers.meta]
  runtime = "nodejs"

[[analyzers]]
name = "secrets"
enabled = true

[[transformers]]
name = "prettier"
enabled = true
