name = "dubular-site"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2025-09-28"
compatibility_flags = ["nodejs_compat"]


[[d1_databases]]
binding="DB"
database_name="dubular-db"
database_id="e26195c7-2b3b-4804-9c78-298daf52dda9"
[vars]
NEXT_PUBLIC_CLERK_SIGN_IN_URL = "/sign-in"
NEXT_PUBLIC_CLERK_SIGN_UP_URL = "/sign-up"
NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL = "/"
NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL = "/"
