name = "dubular-beta"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[pages]
functions = ".open-next/server-functions"
routes = ".open-next/_routes.json"

