name = "dubular-site"
compatibility_date = "2024-09-01"

# Cloudflare Pages artifact (static) produced by next-on-pages
pages_build_output_dir = ".vercel/output/static"

# Example: add environment vars used at runtime (optional)
# [vars]
# SOME_PUBLIC_KEY = "..."

# Example: add bindings later if you use KV/D1/R2 (optional)
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
