name = "dubular-beta"
compatibility_date = "2025-08-30"
compatibility_flags = ["nodejs_compat"]
# Cloudflare Pages expects this when using wrangler.toml with Next on Pages:
pages_build_output_dir = ".vercel/output"
