name = "dubular-beta"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[pages]
functions = ".open-next/server-functions"
output_dir = ".open-next"

[[pages.routes]]
include = ["/*"]
exclude = ["/_static/*", "/favicon.ico"]
