# Minimal config for Cloudflare Pages Functions
# (Do NOT include workers_dev/account_id/type/routes/etc)
name = "dubular-beta"  # optional/ignored by Pages
compatibility_date = "2025-08-30"
compatibility_flags = ["nodejs_compat"]

# Optional: define env vars here if needed
# [vars]
# MY_ENV = "value"
