name = "dubular-beta"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".open-next"

[build]
command = "npx open-next@3.1.3 build"

[build.upload]
format = "service-worker"
dir = ".open-next/server-functions"

[[routes]]
pattern = "/*"
